spring.dataSource.url: jdbc:mysql://localhost:3306/todolistlib
spring.dataSource.username: root
spring.dataSource.password: jdlYSSvhsdNrhS0EP02H
spring.jpa.hibernate.ddl-auto: none
someParameter:
  value: 123

